# Generated by Django 4.2.4 on 2023-09-03 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('suministro', models.CharField(max_length=50)),
                ('nserie', models.CharField(max_length=50)),
                ('marcaMedidor', models.CharField(max_length=50)),
                ('tarifa', models.CharField(max_length=20)),
                ('fases', models.IntegerField(default=0)),
                ('sed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suministro', models.CharField(max_length=50)),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('valor_lectura', models.FloatField()),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturas.medidor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
